# fly.toml app configuration file generated for technotopia-bot-misty-night-7702 on 2024-01-08T07:51:40-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "technotopia-bot"
primary_region = "ord"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

